# Generated by Django 5.0 on 2023-12-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('meta', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to='media/')),
            ],
        ),
    ]
