# Generated by Django 5.0 on 2023-12-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('images', models.FileField(upload_to='media/')),
            ],
        ),
    ]
