# Generated by Django 5.0 on 2023-12-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasapp', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
